function sinal_filtrado = filtgama(sinal)

b1 = designfilt('highpassiir', 'StopbandFrequency', 30, ...
               'PassbandFrequency', 30.2, 'StopbandAttenuation', 60, ...
               'PassbandRipple', 0.5, 'SampleRate', 160, ...
               'DesignMethod', 'cheby2');
b2 = designfilt('lowpassiir', 'PassbandFrequency', 60, ...
               'StopbandFrequency', 60.2, 'StopbandAttenuation', 60, ...
               'PassbandRipple', 0.5, 'SampleRate', 160, ...
               'DesignMethod', 'cheby2');
% freqz(b1)
% freqz(b2)

sinal_filtrado = filtfilt(b1, sinal(1,:));  
sinal_filtrado = filtfilt(b2, sinal_filtrado(1,:));