function sinal_filtrado = filt0_30(sinal)

b2 = designfilt('lowpassiir', 'PassbandFrequency', 30, ...
               'StopbandFrequency', 30.2, 'StopbandAttenuation', 60, ...
               'PassbandRipple', 0.5, 'SampleRate', 160, ...
               'DesignMethod', 'cheby2');
d1 = designfilt('highpassiir', 'StopbandFrequency', 0.3, ...
               'PassbandFrequency', 0.5, 'StopbandAttenuation', 60, ...
               'PassbandRipple', 0.5, 'SampleRate', 160, ...
               'DesignMethod', 'cheby2');
% freqz(b2)
% freqz(d1)

sinal_filtrado = filtfilt(b2, sinal(1,:));  
sinal_filtrado = filtfilt(d1, sinal_filtrado(1,:));