function sinal_filtrado = filttetha(sinal)

t1 = designfilt('highpassiir', 'StopbandFrequency', 3.8, ...
               'PassbandFrequency', 4, 'StopbandAttenuation', 60, ...
               'PassbandRipple', 0.5, 'SampleRate', 160, ...
               'DesignMethod', 'cheby2');
t2 = designfilt('lowpassiir', 'PassbandFrequency', 8, ...
               'StopbandFrequency', 8.2, 'StopbandAttenuation', 60, ...
               'PassbandRipple', 0.5, 'SampleRate', 160, ...
               'DesignMethod', 'cheby2');
% freqz(t1)
% freqz(t2)

sinal_filtrado = filtfilt(t1, sinal(1,:));  
sinal_filtrado = filtfilt(t2, sinal_filtrado(1,:));